---
name: 'checks'

'on':
  pull_request:
    branches:
      - 'main'

jobs:
  linting:
    uses: broadinstitute/shared-workflows/.github/workflows/python-lint.yaml@v5.0.1
    with:
      use_pylama: false
      use_ruff: true
